language: php
php:
  - 7.3
services:
  - memcached
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - sudo apt-get update
  - sudo apt-get install php-memcached
  - gem install mailcatcher
  - phpenv config-add travis.php.ini
  - mailcatcher
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - psql -c 'create database rss_db_test;' -U postgres -p 5433
  - cp .env.travis .env
  - php artisan key:generate
script:
  - php artisan migrate --seed
  - ./vendor/bin/phpunit --coverage-clover clover.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
